/* 사건 */
CREATE TABLE ACCIDENT(
	ACCIDENT_ID INTEGER PRIMARY KEY,	-- 사건번호
    ACC_DATE DATE NOT NULL,				-- 날짜
    ACC_TIME TIME NOT NULL,				-- 시간
    AIRPORT VARCHAR(30),				-- 공항
    FLIGHT_PHASE VARCHAR(10) NOT NULL,	-- 비행단계
    MODEL_NAME VARCHAR(50) NOT NULL, 	-- 모델명
    WEATHER_ID INTEGER NOT NULL,		-- 날씨ID
    BIRD_ID VARCHAR(10) NOT NULL,		-- 조류종ID
    FOREIGN KEY(WEATHER_ID) REFERENCES WEATHER(WEATHER_ID),
	FOREIGN KEY(BIRD_ID) REFERENCES BIRD(BIRD_ID),
    FOREIGN KEY(MODEL_NAME) REFERENCES AIRCRAFT(MODEL_NAME)
);
