/* 항공기 정보 */
CREATE TABLE AIRCRAFT(
	MODEL_NAME VARCHAR(50) PRIMARY KEY,				-- 모델명
    WEIGHT VARCHAR(20) NOT NULL,					-- 무게
    CLASS VARCHAR(20) NOT NULL,						-- 클래스
    ENGINE_1_EXSITS BOOLEAN NOT NULL DEFAULT FALSE,	-- 1번엔진 존재유무
    ENGINE_2_EXSITS BOOLEAN NOT NULL DEFAULT FALSE,	-- 2번엔진 존재유무
    ENGINE_3_EXSITS BOOLEAN NOT NULL DEFAULT FALSE,	-- 3번엔진 존재유무
    ENGINE_4_EXSITS BOOLEAN NOT NULL DEFAULT FALSE	-- 4번엔진 존재유무
);
