INSERT INTO AIRCRAFT (MODEL_NAME, WEIGHT, CLASS, ENGINE_1_EXSITS, ENGINE_2_EXSITS, ENGINE_3_EXSITS, ENGINE_4_EXSITS) VALUES
('B-737', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('B-737-700', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('B-737-800', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('B-737-900', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('ATR-42', 'Light', '여객기', TRUE, TRUE, FALSE, FALSE),
('MERLIN IV', 'Light', '특수목적기', TRUE, TRUE, FALSE, FALSE),
('BE-1900', 'Light', '여객기', TRUE, TRUE, FALSE, FALSE),
('EMB-170', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('CRJ900', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('CRJ100/200', 'Light', '여객기', TRUE, TRUE, FALSE, FALSE),
('GULFSTREAM IV', 'Medium', '특수목적기', TRUE, TRUE, FALSE, FALSE),
('A-319', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('A-320', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('A-321', 'Medium', '여객기', TRUE, TRUE, FALSE, FALSE),
('B-777', 'Heavy', '여객기', TRUE, TRUE, FALSE, FALSE),
('B-747', 'Heavy', '여객기', TRUE, TRUE, TRUE, TRUE),
('A-330', 'Heavy', '여객기', TRUE, TRUE, FALSE, FALSE),
('A-380', 'Heavy', '여객기', TRUE, TRUE, TRUE, TRUE),
('DHC-8', 'Light', '여객기', TRUE, TRUE, FALSE, FALSE),
('CITATION', 'Light', '특수목적기', TRUE, TRUE, FALSE, FALSE);
