INSERT INTO BIRD (BIRD_ID, BIRD_NAME, BIRD_SIZE) VALUES
('ROC_2', 'Rock pigeon', 'MEDIUM'),
('CAN_3', 'Canada goose', 'LARGE'),
('AME_1', 'American robin', 'SMALL'),
('HOR_1', 'Horned lark', 'SMALL'),
('KIL_2', 'Killdeer', 'MEDIUM'),
('BAR_1', 'Barn swallow', 'SMALL'),
('RED_1', 'Red-eyed vireo', 'SMALL'),
('BLU_1', 'Blue-headed vireo', 'SMALL'),
('EAS_2', 'Eastern meadowlark', 'MEDIUM'),
('SON_1', 'Song sparrow', 'SMALL'),
('CHI_1', 'Chimney swift', 'SMALL'),
('WES_1', 'Western tanager', 'SMALL'),
('AME_2', 'American crow', 'MEDIUM'),
('BAL_3', 'Bald eagle', 'LARGE'),
('CAR_1', 'Cardinal', 'SMALL'),
('DOW_1', 'Downy woodpecker', 'SMALL'),
('EUR_1', 'European starling', 'SMALL'),
('HOU_1', 'House finch', 'SMALL'),
('GRE_3', 'Great blue heron', 'LARGE'),
('RUB_1', 'Ruby-throated hummingbird', 'SMALL');
