/* 피해정보 */
CREATE TABLE DAMAGE(
	IMPACT_AREA VARCHAR(20),				-- 충돌부위
    ACCIDENT_ID INTEGER,					-- 사건번호
    IMPACT_FORCE DECIMAL(6,2) NOT NULL,		-- 충격량
    DAMAGE_LEVEL VARCHAR(5) NOT NULL,		-- 피해수준
    PRIMARY KEY(IMPACT_AREA, ACCIDENT_ID),
    FOREIGN KEY(ACCIDENT_ID) REFERENCES ACCIDENT(ACCIDENT_ID)
);
