/* 삽입하다 */
CREATE TABLE INSERT_ACC(
	USER_ID VARCHAR(20),	-- ID
    ACCIDENT_ID INTEGER,	-- 사건번호
    INSERT_DT DATETIME,		-- 삽입일시
    PRIMARY KEY(USER_ID, ACCIDENT_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);
