/* 참여하다 */
CREATE TABLE PARTICIPATE(
	USER_ID VARCHAR(20),	-- ID
    RESEARCH_ID INTEGER,	-- 연구결과ID
    PRIMARY KEY(USER_ID, RESEARCH_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID)
);
