/* 참고하다 */
CREATE TABLE REFER(
	ACCIDENT_ID INTEGER,	-- 사건번호
    RESEARCH_ID INTEGER,	-- 연구결과ID
	PRIMARY KEY(ACCIDENT_ID, RESEARCH_ID),
    FOREIGN KEY(ACCIDENT_ID) REFERENCES ACCIDENT(ACCIDENT_ID),
    FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID)
);
