/* 조회하다 */
CREATE TABLE SEARCH_ACC(
	USER_ID VARCHAR(20),	-- ID
    ACCIDENT_ID INTEGER,	-- 사건번호
    SEARCH_DT DATETIME,		-- 조회일시
    PRIMARY KEY(USER_ID, ACCIDENT_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);
