/* 날씨 */
CREATE TABLE WEATHER(
	WEATHER_ID INTEGER PRIMARY KEY,		-- 날씨ID
    WEATHER VARCHAR(20) NOT NULL,		-- 날씨
    PRECIPITATION DECIMAL(5,2),			-- 강수량
    WIND_SPEED DECIMAL(5,2) NOT NULL	-- 풍속
);
