SELECT
	ACCIDENT.ACCIDENT_ID, ACCIDENT.FLIGHT_PHASE,
    AIRCRAFT.MODEL_NAME, AIRCRAFT.CLASS,
    BIRD.BIRD_NAME, BIRD.BIRD_SIZE,
    DAMAGE.IMPACT_AREA, DAMAGE.IMPACT_FORCE, DAMAGE.DAMAGE_LEVEL
FROM ACCIDENT
JOIN AIRCRAFT ON ACCIDENT.MODEL_NAME = AIRCRAFT.MODEL_NAME
JOIN BIRD ON ACCIDENT.BIRD_ID = BIRD.BIRD_ID
JOIN DAMAGE ON ACCIDENT.ACCIDENT_ID = DAMAGE.ACCIDENT_ID
WHERE AIRCRAFT.CLASS = '여객기';